### ISSUE TITLE
Do not look for derived parameters in 'generated quantities' block

### ISSUE THREAD

**Issue by cdmuir** [poissonconsulting/smbr#6]
see note in parameters.R, line ~#28

**Comment by joethorley** [comment]
This is an important change

**Comment by cdmuir** [comment]
After discussion with Joe on July 10, we decided smbr should completely ignore generated quantities block (I have made these changes and removed notes) and all calculations should be done in 'new_expr' block. I'm leaving open because I want to decide whether we should automatically remove (and generate a warning) when Stan code with `generated quantities` is passed to smbr?

Also note that derived parameters should be defined in Stan's `transformed parameters` block.

**Comment by joethorley** [comment]
A warning that being ignored seems useful.

**Comment by joethorley** [comment]
Actually there isn't a natural place to throw the warning plus its easy to overwhelm users with message. On reflection I think we just silently ignore. Folks will get it once they grok the mbr way.
